## Introduction to Numpy

In [30]:
#Why Numpy? there are two main reason , 
#Numpy functionality is based on C language , therefore the numerical operations are faster 
#Numpy helps to easily perform different operations on ndarrays due to the concept of broadcasting

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Creating numpy array of 1,2,3 Dimension
a1=np.array([1,2,3])
a2=np.array([[1,2,3],
            [4,5,6]])
a3=np.array([[[1,2,3],
             [4,5,6]],
            [[7,8,9],
            [10,11,12]]])

In [4]:
#checking the types of each array
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [5]:
#checking the dimensions of each array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [6]:
#checking size of each arrays
len(a1),len(a2),len(a3)

(3, 2, 2)

In [7]:
#checking the type of each arrays
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Creating Arrays in numpy

In [8]:
#creating array containing only ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#Creating array containing only zeros.
# If u dont know the parameter of the method press Shift+Tab to display the doc string of that method
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#Creating a 1D array within a range 
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
#Creating a nDArray with random number between a range from(inclusive) - to(exclusive)
random_array=np.random.randint(0,10,size=(3,3))

In [12]:
random_array

array([[8, 6, 2],
       [0, 3, 5],
       [0, 5, 1]], dtype=int32)

In [13]:
random_array=np.random.randint(0,10,size=(2,3,3))

In [14]:
random_array

array([[[5, 7, 0],
        [0, 8, 5],
        [8, 8, 0]],

       [[7, 7, 5],
        [8, 7, 9],
        [8, 2, 5]]], dtype=int32)

In [15]:
#Creating Pseudo random numbers
#if we are going to share the notebook with other dev, the random numbers are always changing after each execution , instead we will generate a random and keep it constant for a given seed
np.random.seed(seed=0)
random_array2=np.random.randint(10,size=(3,3))
random_array2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [16]:
np.random.seed(seed=0)
random_array3=np.random.randint(10,size=(3,3))
random_array3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [17]:
#see as the seed is same the genrated array is also same , 
#Lets change the seed to something else suppose seed=4
np.random.seed(seed=4)
random_array4=np.random.randint(10,size=(3,3))
random_array4

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7]], dtype=int32)

In [18]:
#different random array is generated

## Manipulating and Comparing Arrays

### Arithmetic

In [19]:
a1

array([1, 2, 3])

In [22]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [24]:
#Sum of two arrays

In [23]:
a1+ones

array([2., 3., 4.])

## Difference Between Python `sum()` and numpy `np.sum()`

In [25]:
#Python sum() is slower to np.sum()
#use python sum() only for python dataypes 
#use np.sum() only for numpy datatype

In [26]:
#Visual representation of comparison, %timeit is a special method in jupyter to tell the time taken to execute that cell
massive_array=np.random.random(10000)
massive_array[:10]

array([0.22450592, 0.69842024, 0.90317852, 0.6329631 , 0.00515915,
       0.57235649, 0.36149634, 0.60413194, 0.39176619, 0.81194775])

In [27]:
#applying python Sum() with %timeit to check the execution time
%timeit sum(massive_array)

1.14 ms ± 74.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [29]:
#applying np.sum()
%timeit np.sum(massive_array)

11.1 μs ± 357 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [35]:
#calculating standard deviation 
#Standard Deviation is the Measure of how Spread out the Group of numbers is from the Mean
std=np.std(a2)

In [36]:
#calculating variance
#Variance is the Measure of Average Degree by which the number differs from the mean 
#Higher Variance=Higher range of Numbers 
#Lower Variance=Lower range of Numbers
var=np.var(a2)

In [38]:
#Standard deviation =sqrt(var)
std==np.sqrt(var)

np.True_

## Reshaping and Transposing Arrays

In [39]:
#using reshape method
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
#it will fail if we try to find the product a2 *a3 
#Rules for Broadcasting:
#1. The shape has to be same or
#2. Either of dimension has to be 1
a2.shape,a3.shape

((2, 3), (2, 2, 3))

In [44]:
a2_reshaped=a2.reshape(1,2,3)

In [45]:
a2_reshaped

array([[[1, 2, 3],
        [4, 5, 6]]])

In [46]:
a2_reshaped*a3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 7, 16, 27],
        [40, 55, 72]]])

In [47]:
#Transposing the array
a2.T,a2.T.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

## Dot Product Vs Element Wise Product

In [48]:
#Creating some random numbers in matrices
np.random.seed(seed=0)
mat1=np.random.randint(10,size=(3,4))
mat2=np.random.randint(10,size=(3,4))
mat1.shape,mat2.shape

((3, 4), (3, 4))

In [49]:
mat1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [50]:
mat2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]], dtype=int32)

In [51]:
#Element Wise Product (Hadamard Multiplication)
mat1*mat2

array([[40,  0,  3, 18],
       [49, 63, 24,  5],
       [10, 36, 56, 54]], dtype=int32)

In [52]:
#Dot Product: the dim. of Column of Matrice 1 should be = to dim. of Row in Matrice 2
#but here both the matrices have dim (3,4)
#To make it work we need to tranpose one matrice (3,4).(4,3)=(3,3)
mat3=np.dot(mat1,mat2.T)
mat3,mat3.shape

(array([[ 61,  62,  76],
        [161, 141, 185],
        [ 91, 104, 156]], dtype=int32),
 (3, 3))

## Exercise: Nut Butter Store Sales

In [54]:
#Creating the data from scratch
np.random.seed(0)
store_sales=np.random.randint(10,size=(5,3))
store_sales

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [56]:
#Creating a dataframe index=5 days of the week, labels=types of butter
store_sales_dataframe=pd.DataFrame(store_sales,
                                  index=["Mon","Tues","Wed","Thurs","Fri"],
                                  columns=["Almond Butter","Peanut Butter","Cashew Butter"])
store_sales_dataframe

       Almond Butter  Peanut Butter  Cashew Butter
Mon                5              0              3
Tues               3              7              9
Wed                3              5              2
Thurs              4              7              6
Fri                8              8              1

In [64]:
# Creating price per jar for the types of butter
np.random.seed(0)
jar_price=np.random.randint(10,14,size=(1,3))
jar_price

array([[10, 13, 11]], dtype=int32)

In [65]:
#Creating Dataframe for this jar_price
jar_price_dataframe=pd.DataFrame(jar_price,
                                index=["Price"],
                                columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [66]:
jar_price_dataframe

       Almond Butter  Peanut Butter  Cashew Butter
Price             10             13             11

In [68]:
#Calculating total amount sold per day using dot product and storing it in Total ($) column
store_sales_dataframe["Total ($)"]=np.dot(store_sales_dataframe,jar_price_dataframe.T)

In [69]:
store_sales_dataframe

       Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon                5              0              3         83
Tues               3              7              9        220
Wed                3              5              2        117
Thurs              4              7              6        197
Fri                8              8              1        195

## Comparison

In [70]:
a1

array([1, 2, 3])

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a1>=a2

array([[ True,  True,  True],
       [False, False, False]])

In [73]:
bool_array=a1>=a2
type(bool_array),bool_array.dtype

(numpy.ndarray, dtype('bool'))

## Sorting

In [77]:
# Difference Between np.sort() and np.argsort()
#np.sort() return the sorted array by default row wise sort 
#np.argsort() returns the index of the array 
np.sort(random_array),np.argsort(random_array)

(array([[[0, 5, 7],
         [0, 5, 8],
         [0, 8, 8]],

        [[5, 7, 7],
         [7, 8, 9],
         [2, 5, 8]]], dtype=int32),
 array([[[2, 0, 1],
         [0, 2, 1],
         [2, 0, 1]],

        [[2, 0, 1],
         [1, 0, 2],
         [1, 2, 0]]]))

In [85]:
np.random.seed(0)
random_array2=np.random.randint(10,size=(5,3))
random_array2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [86]:
#Checking the argmax(),argmin() methods in numpy
np.argmin(random_array2,axis=0)
#axis=0 means column wise, for first column the index of the min number

array([1, 0, 4])

In [87]:
#similarly for axis=1 it will display the index of min value for row
np.argmin(random_array2,axis=1)

array([1, 0, 2, 0, 2])

In [88]:
#similar will happen for np.argmax() method