In [1]:
# Reference Note Book : https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/scikit-learn-what-were-covering.ipynb

# Introduction to Scikit-Learn

## 0. An End to End Scikit-Learn Workflow

In [2]:
# Importing data 
import pandas as pd
heart_disease=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# Creating Features Matrix
X=heart_disease.drop("target",axis=1)
# Creating Label
Y=heart_disease["target"]

In [4]:
# Choosing a model and hyperparameters
# Hyperparameters are like dials of the model with which we can do model tunining to make it better or worse :D
from sklearn.ensemble import RandomForestClassifier 
clf=RandomForestClassifier()
#keeping default hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# Fit the Model to the Training Data
# For that we need to split the data into train and test

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [6]:
# Now Lets Fit the model to train data
clf.fit(x_train,y_train)

RandomForestClassifier()

In [7]:
# Now lets Predict some output on test data
y_preds=clf.predict(x_test)
y_preds

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [8]:
y_test

17     1
235    0
122    1
111    1
110    1
      ..
38     1
86     1
33     1
193    0
190    0
Name: target, Length: 61, dtype: int64

In [9]:
# Time for Evaluation on both train data and test data
clf.score(x_train,y_train)

1.0

In [10]:
# Ahhh! Maximum accuracy on training data set 
# lets Score it on test data 
clf.score(x_test,y_test)

0.8360655737704918

In [11]:
# 78% accuracy ok not bad

In [12]:
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score

In [13]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.76      0.88      0.81        25
           1       0.91      0.81      0.85        36

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.85      0.84      0.84        61

In [14]:
confusion_matrix(y_test,y_preds)

array([[22,  3],
       [ 7, 29]])

In [15]:
accuracy_score(y_test,y_preds)

0.8360655737704918

In [16]:
import numpy as np

In [17]:
# Improving The model
# There is a Parameter n-estimators=100 .its default value
# Trying with different n-estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Using n-estimators = {i}")
    clf=RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"The accuracy with {i} Estimators is {clf.score(x_test,y_test)*100:.2f}")

Using n-estimators = 10
The accuracy with 10 Estimators is 78.69
Using n-estimators = 20
The accuracy with 20 Estimators is 81.97
Using n-estimators = 30
The accuracy with 30 Estimators is 77.05
Using n-estimators = 40
The accuracy with 40 Estimators is 81.97
Using n-estimators = 50
The accuracy with 50 Estimators is 80.33
Using n-estimators = 60
The accuracy with 60 Estimators is 81.97
Using n-estimators = 70
The accuracy with 70 Estimators is 81.97
Using n-estimators = 80
The accuracy with 80 Estimators is 78.69
Using n-estimators = 90
The accuracy with 90 Estimators is 83.61

In [18]:
# So we are getting good accuracy when i=40,60,70,80

In [19]:
# Saving a model and loading it 
import pickle

# pickle.dump(clf,open("random_forest_demo_model1.pkl","wb"))

In [20]:
load_model=pickle.load(open("random_forest_demo_model1.pkl","rb"))
load_model.score(x_test,y_test)

0.9836065573770492

In [21]:
#Good job we saved and loaded the model

# Deep Dive into each steps of end to end WorkFlow

## 1. Getting the Data ready to be used in Machine Learning

Three steps we have to follow:

    1. Splitting the Data into Features and Labels `X` and `Y`
    2. Filling (Also called imputing) and disregarding the missing values
    3. Converting Non-Numerical Values to Numerical data (this is known as Feature Encoding)

In [22]:
# lets view the data 
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
# Lets Split it into Features X and Labels Y
X=heart_disease.drop("target",axis=1)
Y=heart_disease["target"]

In [24]:
#Split the data into train test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [25]:
#Printing the Shapes of each split
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [43]:
# As the heart disease data does not have any missing value we are going to import another dataset
car_sales=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [44]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

In [45]:
# Here we are going to split the data into labels X (Features) and Y (Label=Price)
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

In [46]:
# Now we are going to split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [47]:
# Importing a model
from sklearn.ensemble import RandomForestRegressor # earlier we used RandomForestClassifier this time Regressor why ? cz we are going to predict some numeric data

model=RandomForestRegressor() #Initialising the Model
model.fit(x_train,y_train)  #fitting the model
model.score(x_test,y_test)  #scoring the model

ValueError: could not convert string to float: 'Toyota'

In [48]:
# AAHH! what is this error now. OOH we need to convert the string data into numeric data 
# Let's see how scikit learn help us to do that

In [49]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")
transformed_X=transformer.fit_transform(X)

In [55]:
#What is One Hot Encoder ? -> it converts the category into columns and put zero and one respectively
#E.g: for a car it has colour red
#there will be other colours too, White, Black,Red
# to represent the colour <Column Name=0 or 1>, White=0, Black=0 and Red=1

In [50]:
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [51]:
# Converting to Dataframe
transformed_X_dataframe=pd.DataFrame(transformed_X)
transformed_X_dataframe

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [52]:
# Lets Refit the model

x_train,x_test,y_train,y_test=train_test_split(transformed_X,
                                              Y,
                                              test_size=0.2)

In [53]:
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.30754088750442443

In [58]:
import sklearn
print(sklearn.__version__) #as per the notes from Course 0.23+ Sklearn lib automatically handles NaN or Null values lets try

1.9.0

### 1.2 What if there were Missing Data?

1. We can fill them with some Values also called Imputation. Cons: Those filled data are not real
2. We can remove the missing data. Cons: Decrease in size of Data

In [59]:
#importing missing car sales data
car_sales=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales-extended-missing-data.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [60]:
# In a huge data set how to know if there are any missing data?
# we can use this :
car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [61]:
# Here it shows the number of missing data for each columns

In [62]:
#Creating X and Y
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

### Option 1: Filling Missing Data using Pandas

In [68]:
# Fill the "Make" Column 
car_sales["Make"]=car_sales["Make"].fillna("missing")

# Fill the "Colour" Column
car_sales["Colour"]=car_sales["Colour"].fillna("missing")

# Fill the "Odometer (KM)" Column
car_sales["Odometer (KM)"]=car_sales["Odometer (KM)"].fillna(car_sales["Odometer (KM)"].mean())

#Fill the "Doors" Column
car_sales["Doors"]=car_sales["Doors"].fillna(4)

In [69]:
car_sales.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [70]:
# So we have Filled the Missing data for the Categories Column, Then what about the Price Column
# As we are going to Predict the price column we are not going to fill the data with some non real value , we are going to Drop it
car_sales=car_sales.dropna()

In [72]:
car_sales.isna().sum() #Finally no more Missing Data, Great Job!!

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [73]:
#Creating X and Y
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

In [78]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")
transformed_X=transformer.fit_transform(X)

In [79]:
transformed_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

### Option 2: Filling Data using Scikit Learn

In [ ]:
#Reimporting the Dataset