In [1]:
# Reference Note Book : https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/scikit-learn-what-were-covering.ipynb

# Introduction to Scikit-Learn

## 0. An End to End Scikit-Learn Workflow

In [1]:
# Importing data 
import pandas as pd
heart_disease=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
# Creating Features Matrix
X=heart_disease.drop("target",axis=1)
# Creating Label
Y=heart_disease["target"]

In [3]:
# Choosing a model and hyperparameters
# Hyperparameters are like dials of the model with which we can do model tunining to make it better or worse :D
from sklearn.ensemble import RandomForestClassifier 
clf=RandomForestClassifier()
#keeping default hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# Fit the Model to the Training Data
# For that we need to split the data into train and test

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [5]:
# Now Lets Fit the model to train data
clf.fit(x_train,y_train)

RandomForestClassifier()

In [6]:
# Now lets Predict some output on test data
y_preds=clf.predict(x_test)
y_preds

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0])

In [7]:
y_test

49     1
10     1
135    1
65     1
224    0
      ..
134    1
299    0
21     1
105    1
184    0
Name: target, Length: 61, dtype: int64

In [8]:
# Time for Evaluation on both train data and test data
clf.score(x_train,y_train)

1.0

In [9]:
# Ahhh! Maximum accuracy on training data set 
# lets Score it on test data 
clf.score(x_test,y_test)

0.8524590163934426

In [10]:
# 78% accuracy ok not bad

In [11]:
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score

In [12]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

In [13]:
confusion_matrix(y_test,y_preds)

array([[24,  5],
       [ 4, 28]])

In [14]:
accuracy_score(y_test,y_preds)

0.8524590163934426

In [15]:
import numpy as np

In [16]:
# Improving The model
# There is a Parameter n-estimators=100 .its default value
# Trying with different n-estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Using n-estimators = {i}")
    clf=RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"The accuracy with {i} Estimators is {clf.score(x_test,y_test)*100:.2f}")

Using n-estimators = 10
The accuracy with 10 Estimators is 78.69
Using n-estimators = 20
The accuracy with 20 Estimators is 78.69
Using n-estimators = 30
The accuracy with 30 Estimators is 78.69
Using n-estimators = 40
The accuracy with 40 Estimators is 86.89
Using n-estimators = 50
The accuracy with 50 Estimators is 83.61
Using n-estimators = 60
The accuracy with 60 Estimators is 86.89
Using n-estimators = 70
The accuracy with 70 Estimators is 85.25
Using n-estimators = 80
The accuracy with 80 Estimators is 85.25
Using n-estimators = 90
The accuracy with 90 Estimators is 81.97

In [17]:
# So we are getting good accuracy when i=40,60,70,80

In [18]:
# Saving a model and loading it 
import pickle

# pickle.dump(clf,open("random_forest_demo_model1.pkl","wb"))

In [19]:
load_model=pickle.load(open("random_forest_demo_model1.pkl","rb"))
load_model.score(x_test,y_test)

0.9672131147540983

In [20]:
#Good job we saved and loaded the model

# Deep Dive into each steps of end to end WorkFlow

## 1. Getting the Data ready to be used in Machine Learning

Three steps we have to follow:

    1. Splitting the Data into Features and Labels `X` and `Y`
    2. Filling (Also called imputing) and disregarding the missing values
    3. Converting Non-Numerical Values to Numerical data (this is known as Feature Encoding)

In [21]:
# lets view the data 
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [22]:
# Lets Split it into Features X and Labels Y
X=heart_disease.drop("target",axis=1)
Y=heart_disease["target"]

In [23]:
#Split the data into train test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [24]:
#Printing the Shapes of each split
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [25]:
# As the heart disease data does not have any missing value we are going to import another dataset
car_sales=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [26]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

In [27]:
# Here we are going to split the data into labels X (Features) and Y (Label=Price)
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

In [28]:
# Now we are going to split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [29]:
# Importing a model
from sklearn.ensemble import RandomForestRegressor # earlier we used RandomForestClassifier this time Regressor why ? cz we are going to predict some numeric data

model=RandomForestRegressor() #Initialising the Model
model.fit(x_train,y_train)  #fitting the model
model.score(x_test,y_test)  #scoring the model

ValueError: could not convert string to float: 'Toyota'

In [30]:
# AAHH! what is this error now. OOH we need to convert the string data into numeric data 
# Let's see how scikit learn help us to do that

In [31]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")
transformed_X=transformer.fit_transform(X)

In [32]:
#What is One Hot Encoder ? -> it converts the category into columns and put zero and one respectively
#E.g: for a car it has colour red
#there will be other colours too, White, Black,Red
# to represent the colour <Column Name=0 or 1>, White=0, Black=0 and Red=1

In [33]:
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [34]:
# Converting to Dataframe
transformed_X_dataframe=pd.DataFrame(transformed_X)
transformed_X_dataframe

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [35]:
# Lets Refit the model

x_train,x_test,y_train,y_test=train_test_split(transformed_X,
                                              Y,
                                              test_size=0.2)

In [36]:
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.2330485230539474

In [37]:
import sklearn
print(sklearn.__version__) #as per the notes from Course 0.23+ Sklearn lib automatically handles NaN or Null values lets try

1.9.0

### 1.2 What if there were Missing Data?

1. We can fill them with some Values also called Imputation. Cons: Those filled data are not real
2. We can remove the missing data. Cons: Decrease in size of Data

In [38]:
#importing missing car sales data
car_sales=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales-extended-missing-data.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [39]:
# In a huge data set how to know if there are any missing data?
# we can use this :
car_sales.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [40]:
# Here it shows the number of missing data for each columns

In [41]:
#Creating X and Y
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

### Option 1: Filling Missing Data using Pandas

In [42]:
# Fill the "Make" Column 
car_sales["Make"]=car_sales["Make"].fillna("missing")

# Fill the "Colour" Column
car_sales["Colour"]=car_sales["Colour"].fillna("missing")

# Fill the "Odometer (KM)" Column
car_sales["Odometer (KM)"]=car_sales["Odometer (KM)"].fillna(car_sales["Odometer (KM)"].mean())

#Fill the "Doors" Column
car_sales["Doors"]=car_sales["Doors"].fillna(4)

In [43]:
car_sales.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [44]:
# So we have Filled the Missing data for the Categories Column, Then what about the Price Column
# As we are going to Predict the price column we are not going to fill the data with some non real value , we are going to Drop it
car_sales=car_sales.dropna()

In [45]:
car_sales.isna().sum() #Finally no more Missing Data, Great Job!!

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [46]:
#Creating X and Y
X=car_sales.drop("Price",axis=1)
Y=car_sales["Price"]

In [47]:
# Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")
transformed_X=transformer.fit_transform(X)

In [48]:
transformed_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

### Option 2: Filling Data using Scikit Learn

In [49]:
#Reimporting the Dataset 
car_sales_missing=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

### Best Practice is to handle the missing data after splitting the data into train and test

#### Here we are just going to see the process of handling missing data(Not Recommended in real life workflow)

In [50]:
# Drop the rows with no Price Labels
car_sales_missing.dropna(subset=["Price"],inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [51]:
# Splitting into X and Y
X=car_sales_missing.drop("Price",axis=1)
Y=car_sales_missing["Price"]

In [53]:
# Filling Missing Value using Scikit Learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#Filling Categorical values with "missing" and numerical values with mean
cat_imputer=SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy="mean")

# Defining Columns
cat_features=["Make","Colour"]
door_feature=["Doors"]
num_features=["Odometer (KM)"]

# Create an imputer 
imputer=ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_features),
    ("door_imputer",door_imputer,door_feature),
    ("num_imputer",num_imputer,num_features)
])

In [54]:
#checking the number of missing values in X
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [56]:
# Lets fill now 
filled_X=imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], shape=(950, 4), dtype=object)

In [58]:
# Lets conver the array to a datafram 
car_sales_filled=pd.DataFrame(filled_X,columns=["Make","Colour","Doors","Odometer (KM)"])
car_sales_filled.head()

     Make Colour Doors Odometer (KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [59]:
# Is there any missing data Now ?
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [60]:
# As we have handled the Missing Values lets convert the non-numerical data to numerical usng OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")
transformed_X=transformer.fit_transform(car_sales_filled)
transformed_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

In [61]:
# now lets initialise the model and fit it 
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(transformed_X,Y,test_size=0.2)
model=RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.22532301070502558

In [62]:
# Great Job!! :D

## 2. Choosing the right estimator/algorithm for the problem

Some things to note:

    * Sklearn refers to machine learning models, algorithms as estimators
    * Classification Problem: Predicting a Category(heart Disease or Not)
        * Sometime we will see `clf` for classification estimator as a short form
    * Regression Problem: Like predicting a Number (Price of a Car)

![ml_map:model_to_choose](ml_map.svg)

In [63]:
# Follow the above flow chart to select a model for a Problem . Very much Helpful isnt it !!

## 2.1 Picking a Machine Learning Model for a Regression Problem 
Dataset Used California Housing Data from Sklearn: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html

In [65]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [66]:
# So in the above data we have features names and labels, great, lets view it in a Dataframe
housing_dataframe=pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_dataframe

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [68]:
# Lets add the label also that is the price 
housing_dataframe["MedHouseVal"]=housing["target"]
housing_dataframe.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [69]:
housing_dataframe["target"]=housing["target"]
housing_dataframe=housing_dataframe.drop("MedHouseVal",axis=1)
housing_dataframe.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [70]:
# import the model
from sklearn.linear_model import Ridge

# Setting up Random Seed
np.random.seed(42)

# Split the Data into X and Y 
X=housing_dataframe.drop("target",axis=1)
Y=housing_dataframe["target"]

# splitting the X and Y into train and test
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

# Instantiate the model and fit it
model=Ridge()
model.fit(x_train,y_train)

# Score the model
model.score(x_test,y_test)

0.5758549611440126

In [73]:
# Great Job !! Though the Score value is not great
# The Score is based on Coefficient of Determination or R-Square is the default evaluation for Regression model
# Co-efficient of Determination is defined as the statistical measure to assess how strong the linear relationship is between Two Variables or more

In [74]:
### Trying to implement a Different Model on the same data as a part of Experimentation
### Model Name: SVR (Support Vector Regression)

#Import the model 
from sklearn.svm import SVR

# Setting up Random Seed
np.random.seed(42)

# Split the Data into X and Y 
X=housing_dataframe.drop("target",axis=1)
Y=housing_dataframe["target"]

# splitting the X and Y into train and test
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

# Instantiate the model and fit it
model=SVR()
model.fit(x_train,y_train)

# Scoring the model
model.score(x_test,y_test)

-0.01648536010717705

In [75]:
## Lol!! its in negative . But ok we get the workflow :D